//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden üretildiğinde kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1236706017
{


    public partial class admindefault
    {
    }
}
